name: "Emma-Liina Marjakangas"
description: "The Personal Homepage for Emma-Liina Marjakangas"

url: "http://emmaliinamarjakangas.github.io"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
